# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\x11\x63\x61lculator_protoc\"*\n\nNumRequest\x12\r\n\x05num_a\x18\x01 \x01(\x01\x12\r\n\x05num_b\x18\x02 \x01(\x01\"\x1a\n\x08NumReply\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32\xbf\x02\n\x0b\x43\x61lculation\x12H\n\x08\x41\x64\x64ition\x12\x1d.calculator_protoc.NumRequest\x1a\x1b.calculator_protoc.NumReply\"\x00\x12L\n\x0cSubstraction\x12\x1d.calculator_protoc.NumRequest\x1a\x1b.calculator_protoc.NumReply\"\x00\x12N\n\x0eMultiplication\x12\x1d.calculator_protoc.NumRequest\x1a\x1b.calculator_protoc.NumReply\"\x00\x12H\n\x08\x44ivision\x12\x1d.calculator_protoc.NumRequest\x1a\x1b.calculator_protoc.NumReply\"\x00\x42\x14Z\x12\x63\x61lculator_protoc/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022calculator_protoc/'
  _globals['_NUMREQUEST']._serialized_start=39
  _globals['_NUMREQUEST']._serialized_end=81
  _globals['_NUMREPLY']._serialized_start=83
  _globals['_NUMREPLY']._serialized_end=109
  _globals['_CALCULATION']._serialized_start=112
  _globals['_CALCULATION']._serialized_end=431
# @@protoc_insertion_point(module_scope)
